apiVersion: apps/v1
kind: Deployment
metadata:
  name: vueapp-deployment
  labels:
    app: vueapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vueapp
  template:
    metadata:
      labels:
        app: vueapp
    spec:
      containers:
      - name: vueapp
        image: hdarab400/find-pharmacy:pharmacy
        ports:
        - containerPort: 80